name: iOS sample autotests
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      device:
        description: 'Select test device'
        required: true
        type: choice
        options:
          - iPhone 15
          - iPhone 14
          - iPhone 13
      test_plan:
        description: 'Select test plan'
        required: true
        type: choice
        options:
          - TurboCalculator
          - TurboCalculator_2

jobs:
  build:
    name: Build and Test on selected device
    runs-on: qaguru
    
    steps:
      - name: Get current env
        run: env
        
      - name: Checkout
        uses: actions/checkout@v4
   
      - name: Build iOS app
        run:
          fastlane ios app_build device:"${{ github.event.inputs.device }}"
          scheme:"${{ github.event.inputs.test_plan }}"
        
      - name: Run Test Plan tests
        run:
          fastlane ios app_test device:"${{ github.event.inputs.device }}"
          scheme:"${{ github.event.inputs.test_plan }}"
        
      - name: Save xcresult
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 'Report'
          path: 'Report'
          retention-days: 15

      - name: Get commit message
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
        
      - name: Print commit message
        run: echo "${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}" >> $GITHUB_STEP_SUMMARY
