name: iOS sample autotests
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on selected device
    runs-on: qaguru
    strategy:
      matrix:
        device: [iPhone 15, iPhone 14, iPhone 13]
        test_plan: [TurboCalculator, TurboCalculator_2]
   

    steps:
      - name: Get current env
        run: env
        
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get commit message
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
        
      - name: Print commit message
        run: echo "${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}" >> $GITHUB_STEP_SUMMARY
   
      - name: Build iOS app
        run: fastlane ios app_build device:"${{ matrix.device }}" scheme:"${{ matrix.test_plan }}"
        
      - name: Run test plan
        run: fastlane ios app_test device:"${{ matrix.device }}" scheme:"${{ matrix.test_plan }}"
        
      - name: Save xcresult
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 'Report'
          path: 'Report'
          retention-days: 15
